# Generated by Django 4.2.1 on 2024-01-15 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewGroups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=120, unique=True)),
                ('group_description', models.TextField(blank=True, max_length=500, null=True)),
                ('group_members', models.ManyToManyField(related_name='user_groups_membership', to=settings.AUTH_USER_MODEL)),
                ('group_movies', models.ManyToManyField(to='movies.moviedetails')),
            ],
        ),
    ]
