# Generated by Django 4.2.1 on 2024-01-15 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewgroups',
            name='group_members',
            field=models.ManyToManyField(related_name='user_groups_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
