# Generated by Django 4.2.1 on 2024-01-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('review_groups', '0002_alter_reviewgroups_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewgroups',
            name='group_movies',
            field=models.ManyToManyField(to='movies.moviedetails'),
        ),
    ]
