# Generated by Django 4.2.1 on 2024-01-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_profile_picture_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
