# Generated by Django 4.2.1 on 2024-01-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_bio',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
