# Generated by Django 4.2.1 on 2024-01-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, default='Provide a review text.', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(default='Provide a review title.', max_length=255),
        ),
    ]
