# Generated by Django 4.2.1 on 2024-01-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('movie_title', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_poster', models.CharField(blank=True, max_length=255, null=True)),
                ('movie_description', models.TextField(blank=True, max_length=10000, null=True)),
                ('movie_genre', models.JSONField(blank=True, null=True)),
                ('movie_release_date', models.DateField(blank=True, null=True)),
                ('movie_length', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
