# Generated by Django 4.2.1 on 2024-01-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedetails',
            old_name='movie_length',
            new_name='movie_duration',
        ),
        migrations.RemoveField(
            model_name='moviedetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='movie_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
