# Generated by Django 4.2.1 on 2024-01-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='movie_duration',
        ),
    ]
